image: node:latest

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client rsync -y )'

stages:
  - deploy

# lint and test are two different jobs in the same stage.
# This allows us to run these two in parallel and making build faster

deployBackToAWS:
  only:
    - master
  stage: deploy
  before_script: 
     - mkdir -p ~/.ssh     
     - echo -e "$SSH_SECRET_KEY" > ~/.ssh/id_rsa
     - chmod 600 ~/.ssh/id_rsa
     - npm install
  script:
    - npm run generate
    - npm run db:seed
    - npm run build
    - rsync -a -e "ssh -p 22" . ec2-user@3.229.129.81:/home/ec2-user/ticket-backend --delete
    - bash deploy/deploy.sh
  when: manual
