image: node:latest

stages:
  - deploy

cache:
  paths:
  - node_modules/

deployBackToAWS:
  only:
    - master
  stage: deploy
  before_script: 
     - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
     - apt-get update -y
     - apt-get -y install rsync
     - mkdir -p ~/.ssh     
     - echo -e "$SSH_SECRET_KEY" > ~/.ssh/id_rsa
     - chmod 600 ~/.ssh/id_rsa
     - npm install
  script:
    - npm run generate
    - npm run db:seed
    - npm run build
    - rsync -av --progress -e "ssh -o 'StrictHostKeyChecking=no' ec2-user@3.229.129.81" "./" "/home/ec2-user/ticket-backend" --delete
    - bash deploy/deploy.sh
  when: manual
